/* GENERATED by scripts/assets.mjs — do not edit.
 * Add or replace files under /public and this rebuilds automatically.
 * Last scan: 2026-08-06T01:09:28.252Z
 */

export type AssetMap = Record<string, string>;

export const shoeArt: AssetMap = {};

export const shoeModel: AssetMap = {};

export const techMacro: AssetMap = {};

export const techSchematic: AssetMap = {};

export const campaignPoster: AssetMap = {};

export const campaignFilm: AssetMap = {};
