/* GENERATED by scripts/assets.mjs — do not edit.
 * Add or replace files under /public and this rebuilds automatically.
 * Last scan: 2026-08-06T02:53:24.196Z
 */

export type AssetMap = Record<string, string>;

export const shoeArt: AssetMap = {
  "alleys": "/shoes/alleys.webp",
  "reverse": "/shoes/reverse.webp",
  "traktor": "/shoes/traktor.webp"
};

export const shoeModel: AssetMap = {
  "reverse": "/models/reverse.glb"
};

export const techMacro: AssetMap = {};

export const techSchematic: AssetMap = {};

export const campaignPoster: AssetMap = {};

export const campaignFilm: AssetMap = {};

export const brandMark: AssetMap = {};
