#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   ASSET SCANNER
   ---------------------------------------------------------------------------
   Scans /public and writes lib/generated-assets.ts. Runs before dev and
   before build, so dropping a file into the right folder is the entire
   action — there is no flag to flip and no code to edit.

   Placeholder PNGs that are 1x1 pixels are deliberately treated as absent,
   so the committed stand-ins never register as real artwork.
   ═══════════════════════════════════════════════════════════════════════════ */

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, extname, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pub = join(root, "public");

const IMAGE = new Set([".png", ".jpg", ".jpeg", ".webp", ".avif"]);
const VIDEO = new Set([".mp4", ".webm", ".mov"]);

/** PNG width/height from the IHDR chunk, or null for other formats. */
function pngSize(file) {
  try {
    const b = readFileSync(file);
    if (b.length < 24 || b.toString("ascii", 12, 16) !== "IHDR") return null;
    return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
  } catch {
    return null;
  }
}

/** A 1x1 PNG is a stand-in, not artwork. */
function isRealImage(file) {
  if (extname(file).toLowerCase() !== ".png") return true;
  const s = pngSize(file);
  return !s || s.w > 4 || s.h > 4;
}

function list(dir) {
  const p = join(pub, dir);
  if (!existsSync(p)) return [];
  return readdirSync(p).filter((f) => !f.startsWith(".") && f.toLowerCase() !== "readme.md");
}


/** Collect `id -> public path` for one folder, filtered by extension set. */
function collect(dir, exts, { suffix = "", checkReal = false } = {}) {
  const out = {};
  for (const f of list(dir)) {
    const ext = extname(f).toLowerCase();
    if (!exts.has(ext)) continue;
    let id = basename(f, ext);
    if (suffix) {
      if (!id.endsWith(suffix)) continue;
      id = id.slice(0, -suffix.length);
    } else if (id.includes("-schematic")) {
      continue; // handled by its own pass
    }
    if (checkReal && !isRealImage(join(pub, dir, f))) continue;
    out[id] = `/${dir}/${f}`;
  }
  return out;
}

const manifest = {
  shoeArt: collect("shoes", IMAGE, { checkReal: true }),
  shoeModel: collect("models", new Set([".glb", ".gltf"])),
  techMacro: collect("tech", IMAGE, { checkReal: true }),
  techSchematic: collect("tech", new Set([".svg"]), { suffix: "-schematic" }),
  campaignPoster: collect("campaigns", IMAGE, { checkReal: true }),
  campaignFilm: collect("campaigns", VIDEO),
};

const body = `/* GENERATED by scripts/assets.mjs — do not edit.
 * Add or replace files under /public and this rebuilds automatically.
 * Last scan: ${new Date().toISOString()}
 */

export type AssetMap = Record<string, string>;

${Object.entries(manifest)
  .map(([k, v]) => `export const ${k}: AssetMap = ${JSON.stringify(v, null, 2)};`)
  .join("\n\n")}
`;

const target = join(root, "lib", "generated-assets.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, body);

const counts = Object.entries(manifest)
  .map(([k, v]) => `${k}=${Object.keys(v).length}`)
  .join("  ");
console.log(`[assets] ${counts}`);
